### ISSUE TITLE
SMCSuperIO文件缺失；fn+F1/F2调整亮度不可用

### ISSUE THREAD

**Issue by InsOnYou** [TokiharaSay/OMEN-by-HP-3-Hackintosh#1]
电脑型号：暗影精灵3，7300hq

/EFI/OC/Kexts/SMCSuperIO.kext这个文件丢失了，会导致启动失败，希望能补上。

另外，这个版本不能用键盘调整亮度，以前的版本似乎没有这个问题，是因为不再使用ACPI文件调整亮度的原因吗？

**Comment by TokiharaSay** [comment]
是但是我测试这个貌似都是正常的

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Holodusk ***@***.***>
Sent: Sunday, March 21, 2021 1:24:24 AM
To: TokiharaSay/OMEN-by-HP-3-Hackintosh ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TokiharaSay/OMEN-by-HP-3-Hackintosh] SMCSuperIO文件缺失；fn+F1/F2调整亮度不可用 (#1)


电脑型号：暗影精灵3，7300hq

/EFI/OC/Kexts/SMCSuperIO.kext这个文件丢失了，会导致启动失败，希望能补上。

另外，这个版本不能用键盘调整亮度，以前的版本似乎没有这个问题，是因为不再使用ACPI文件调整亮度的原因吗？

―

**Comment by TokiharaSay** [comment]
已经更新回去了

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
